# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 07:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='watch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name=b'created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
